### ISSUE TITLE
Importer fails to import paper in ACM Digital Library

### ISSUE THREAD

**Issue by lauratinnel** [ITI/searcch#101]
**Describe the bug**
The importer supposedly supports DOIs pointing to the ACM Digital Library. Providing such a link fails with an error message saying a manual import is required.

**To Reproduce**
1. Go to Submit Artifact
2. Paste in "https://dl.acm.org/doi/10.1145/3474718.3474719" (no quotes)
3. Click "START IMPORT"

**Expected behavior**
Importer should properly parse the DOI target and populate the import form with found information for refinement by the user.

**Comment by carboxylman** [comment]
I wasn't able to reproduce an error -- my import of that URL just got stuck in the pending state.  This was a new bug in the backend where the scheduler didn't get run on all status updates; fixed in https://github.com/ITI/searcch-backend/commit/66ef8cd9e74f7a259114c29ef6fdf09e968e9ab6 .
