### ISSUE TITLE
"start over" (backend bug) handler should reload current route

### ISSUE THREAD

**Issue by carboxylman** [ITI/searcch#104]
Currently the `Start Over` link goes to the `About` route, or somthing.  We would ideally like to retry *if* at least the initial route load succeeded (if not, we don't want to loop, so have to redirect to somewhere safe).

**Comment by carboxylman** [comment]
I had "backend bug" in the title; that was misleading.  This is not a backend bug; this is a frontend bug in the backend 500 bailout error handling case.

I just think that reloading the current route is the best approach if the route load was initially successful.  Could still lead to a loop, but odds are lower.

**Comment by ckouder** [comment]
Fixed using `window.history.go(0)` in pull request #116

**Comment by ckouder** [comment]
fixed in merge request #116
