### ISSUE TITLE
Automated translation of pdf links for publications in arXiv

### ISSUE THREAD

**Issue by lauratinnel** [ITI/searcch#112]
**Is your feature request related to a problem? Please describe.**
When adding an artifact in arXiv.org, it is not clear which URL to use. Using the ﻿http://arxiv.org/pdf link results in an error. The system wants the ﻿http://arxiv.org/abs link. 

**Describe the solution you'd like**
If the user submits the pdf link, automatically convert it to the ﻿http://arxiv.org/abs link. E.g., 

http://arxiv.org/pdf/2111.07847v1  =>  http://arxiv.org/abs/2111.07847v1 
http://arxiv.org/pdf/2111.07847v1.pdf  => http://arxiv.org/abs/2111.07847v1 

**Describe alternatives you've considered**
Document what the link should be and rely on the user to get it right. This isn't as user-friendly. 

**Additional context**
This issue came out of the 2021 ACSAC BoF.

**Comment by carboxylman** [comment]
Fixed in https://gitlab.flux.utah.edu/searcch/importer/-/commit/3a484c72cb3d6a37a10a6308108a38cfcec7dd6e and https://gitlab.flux.utah.edu/searcch/importer/-/commit/f5ce608cdc1c815ca33e9ffd76c5cf3528808472.
