### ISSUE TITLE
Add button to "claim" ownership of an artifact

### ISSUE THREAD

**Issue by dpemmerich** [ITI/searcch#113]
Add a button that allows a user to "claim" an artifact. This is important in cases where someone else/a 3rd party imports an artifact that they are not owners of. For example, artifacts can be added by anyone even if they aren't owners. When the owner logs in and they see the artifact, they should be able to say it is theirs and tie it to them.

This button _*should not*_ automatically approve the claim. Instead, a notification should go out (email, admin interface, both?) to allow an admin or other approved adjudicator approve the claim. For now, Jelana has volunteered to handle approving this...but we should work out a long-term plan for more than one person being the owner of this process...or allow a current person that is allowed to approve these to give access to another person to approve without needing to update any of the backend code.

**Comment by jelenamirkovic** [comment]
Agreed. If you make it send email to searcch@mailman.isi.edu I can easily create that mailing list and we can add/remove people as easily. The email should have a link to approve. When clicked, that link should take one to an API on searcch portal and approve the request. Similarly, there should be an option to deny the request, which should go to another API that would generate email to user that their request was denied.

**Comment by lauratinnel** [comment]
OR we can use the official SEARCCH email domain. @searcch.cyberexperimentation.org. We probably shouldn't be using email addresses all over the place.

**Comment by ckouder** [comment]
I'd like put the button in `KGArtifactLong` since the card contains a `role` section. So the user interaction should be like this:
1. A user enters `KGArtifactLong`
    1.  If no chips in `Role` section, a `claim ownership` button appears. 
    2. If the `Role` section is not empty, a `claim role` button appears. 
2. While clicking it
    1. If the user doesn't login, jump to login page.
    2. If the button is `claim ownership`, send an email to searcch@mailman.isi.edu
    3. If the button is `claim role`, send an email to someone with approval privilege
3. Notify the user that the request has been sent. Then disable the button to prevent repetitive request.

Do we have a mailing service like [formspree](https://formspree.io/) to handle emails? Or is there a back-end API to do this? Correct me if I'm wrong.

**Comment by dpemmerich** [comment]
how would you plan to track that they had made the request so it doesn't show up the next time they view the artifact?

**Comment by jelenamirkovic** [comment]
You would need some field in DB to track

**Comment by ckouder** [comment]
Can we store the request and its status in the back-end? So we fetch the record every time the user views the artifact. But that also means some works for back-end. I'm not sure if it is good. 

In fact I care more about how to shoot an email. I could either make a `mailto:` link or a call to some third-party mailing services. Personally I prefer the latter since the content is more controllable. But if so we need to decide which service to use, don't we?

... Or maybe I'm over-complicating the question 😢

**Comment by jelenamirkovic** [comment]
I think simple sendmail could send the mail from backend server.

**Comment by carboxylman** [comment]
@jelenamirkovic @dpemmerich I sent you guys a canned test email direct from the production backend via `dma`'s `sendmail`; did you receive it?  It made it to my accounts fine.

We probably should use a real SMTP host in our cyberexperimentation.org domain; we don't want to give isi.edu a bad rep; @lauratinnel do we have a way to send mail from that domain?

**Comment by dpemmerich** [comment]
@carboxylman I have not seen the message. What address did you send it to?

**Comment by carboxylman** [comment]
> @carboxylman I have not seen the message. What address did you send it to?

davidpe@illinois.edu

**Comment by lauratinnel** [comment]
@carboxylman Yes. I may have to add the IP address of the server the domain to the DNS records as an authorized server so the server doesn't get blacklisted.

**Comment by dpemmerich** [comment]
> 

ok, I haven't seen it...it may have been picked up by our campus spam filter. I'll keep an eye out

**Comment by jelenamirkovic** [comment]
I've received the message

**Comment by carboxylman** [comment]
@lauratinnel would it make things easier if we had a `searcch-portal-ops@cyberexperimentation.org` with real creds, so that the portal backend can just securely relay email through the domain's "trusted" SMTP path, make the headers as proper as possible?  We'll just drop the creds into `dma`'s config on the backends, and it can send all the "official" looking mail it wants.

**Comment by lauratinnel** [comment]
I can make a primary email account rather than a forwarder, if that's what you prefer. As long as you can make it authenticate to the SMTP server, then that should be fine. I just can't leave it open to email without auth.

**Comment by carboxylman** [comment]
From a sending perspective, we want a full account and I will make it auth, so if you send me those details when you have time, I will get it set up.  From a receive perspective, we probably want it to act like a mailing list that blasts out to all of us who "want" to be admins.  But the receive side could be left to another day...

**Comment by dpemmerich** [comment]
I can confirm that the test mail @carboxylman sent was picked up by our campus spam filters.... so sending to me was technically successful

**Comment by carboxylman** [comment]
From a backend and frontend perspective, this is a pattern we'll encounter a few times, but for now let's just add a table to track each kind of admin request, like claiming ownership here.  I don't think there will be enough approval-required requests to worry about generalizing.  In the current sqlalchemy model, that would look like

```
class RequestArtifactOwnership(db.Model):
    __tablename__ = "request_artifact_ownership"
    __table_args__ = (
        db.UniqueConstraint("artifact_id", "user_id"),
    )

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    artifact_id = db.Column(db.Integer, db.ForeignKey(
        "artifacts.id"), nullable=False)
    message = db.Column(db.Text, nullable=False)
    ctime = db.Column(db.DateTime, nullable=False)
    pending = db.Column(db.Boolean, nullable=False, default=True)
    approved = db.Column(db.Boolean, nullable=False, default=False)
    approving_user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)
    approval_message = db.Column(db.Text, nullable=True)
    approval_time = db.Column(db.DateTime, nullable=True)

    def __repr__(self):
        return "<RequestArtifactOwnership(id=%r,user_id=%r,artifact_id=%r,pending=%r)>" % (
            self.id, self.user_id, self.artifact_id, self.pending)
```

Backend APIs:
POST /requests/ownership { "artifact_id": <artifact_id>, "user_id": <requesting_user_id>, "message": "<message>" }
  * creates a new ownership request; limit one per user
  * sends mail to SEARCCH admins (maybe just Jelena initially)
GET /requests/ownership?user_id=<user_id>&artifact_id=<artifact_id>&pending=True|False&approved=True|False
  * if invoked by non-admin, user_id should not be supplied or must be the calling user's id
  * should return a paginated list of ownership requests, optionally filtered by user_id, artifact_id, pending, approved field states
GET /requests/ownership/<int:request_ownership_id>
  * Returns request details
PUT /requests/ownership/<int:request_ownership_id> { "approved": <bool>, "approval_message": "<message>" }
  * Initially, admin-only, acts on request, sets pending=False, sets all approv* fields, returns the request obj as prior GET does

**Comment by carboxylman** [comment]
@vivekkarne can you tackle that part?  I can help with the migration if you haven't done that before.

**Comment by carboxylman** [comment]
And the corresponding thinking on the frontend:
  * claim button only shown to logged-in users
  * claim button disable if calling user has a pending request
  * not just a claim button -- but also something that collects a non-zero text input with a justification (we can relax this down the road if we ever get to automatic verification, but for all except the obvious cases, we're going to need some inputs to make admin's job easier)
    - probably "claim" pops a modal with a text field and a brief message that instructs the user to provide some evidence of linkage between the email addr on their user account and an author on the artifact
  * new admin page in frontend to list admin requests (probably tabular, with an easy approve button that pops up a modal with text box to approve/disapprove)
  * admin page in frontend to view details of a request (and for instance to reject with email)

This may be a common pattern for a small number of admin requests, but we don't have to worry about making it into its own component yet, IMO.

**Comment by jelenamirkovic** [comment]
I would just modify one thing. Assuming you meant "disable a claim button on any artifact if a given user has pending claim" I would not do this. A user may have several papers in our archive and wants to claim them all in one go. Of course, if you meant "disable claim button on a given artifact if someone has already claimed it or has a pending claim" then yes, we should do that.

**Comment by vivekkarne** [comment]
Sure, I will be able to take this up.

**Comment by lauratinnel** [comment]
Email address is: searcch.hub@cyberexperimentation.org.
SMTP server: mail.cyberexperimentation.org

Password will be sent via a separate channel.

Will you be hardcoding the TO email addresses, or do you want me to set this up to automatically forward to the right people? If the latter (which I would recommend so that all mailing destinations are managed in one place), please let me know the right email addresses. 

What I could do: set up a series of forwarders based on different needs/functions/roles. You just set the TO address to the right forwarder. That way, if someone leaves the project or a new person joins, we just change it in the same place as we do the other mailing lists/forwarders.

**Comment by dpemmerich** [comment]
this is tied to this branch - https://github.com/ITI/searcch/tree/issue-113

**Comment by lauratinnel** [comment]
This feature is now deployed on hub-dev. DavidJ & I tested it. I believe it is working correctly. It will need to be deployed to the projection environment.

**Comment by tbenzel** [comment]
Great job! Thanks everyone!


Terry Benzel
Director Networking and Cybersecurity
Information Sciences Institute
University of Southern California


From: Laura S Tinnel ***@***.***>
Reply-To: ITI/searcch ***@***.***>
Date: Wednesday, September 14, 2022 at 4:25 PM
To: ITI/searcch ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [ITI/searcch] Add button to "claim" ownership of an artifact (Issue #113)


This feature is now deployed on hub-dev. DavidJ & I tested it. I believe it is working correctly. It will need to be deployed to the projection environment.
