### ISSUE TITLE
bottom information bar and left nav pane have some improper overlapping on smaller screen size

### ISSUE THREAD

**Issue by dpemmerich** [ITI/searcch#132]
**Describe the bug**
on a smaller screen, the lower info pane flows over the main area pane. additionally, the left nav bar flows over the lower information bar
<img width="801" alt="image" src="https://user-images.githubusercontent.com/23170883/171512172-ae8f60d1-797b-4f15-9d81-2e84e953d6f9.png">

**To Reproduce**
1. scroll to bottom of screen
2. shrink window down

**Expected behavior**
left nav pane should not flow over the bottom info bar
bottom info bar should not flow over main area

**Comment by dpemmerich** [comment]
seems that the issue is noticed when you change the screen size after the page has loaded.
but also, the info bar does flow over the back to top button in the search artifacts page no matter if you start on a smaller screen or shrink it after loading

**Comment by carboxylman** [comment]
Fixed in #136 .
