### ISSUE TITLE
Update FAQ to address new identity authentication options

### ISSUE THREAD

**Issue by lauratinnel** [ITI/searcch#145]
Update question: 
'I have code, data, and other artifacts that are all from the same research. How should I submit those to the hub?',

with answer:  
'Generally, code and data should be packaged and submitted separately into logical components, unless the code is used to generate the data. The hub supports the ability to link artifacts that are related. Please see the <a href="https://searcch.cyberexperimentation.org/best-practices">best practices and considerations for SEARCCH hub curation</a> for more information.'

Note that I tried updating the FAQ.vue page, but the master branch did not match what was deployed on hub. or hub-dev. It looks like this still lives in an old branch that should have been merged into master. Somehow it got pushed into production without merging.

This update needs to be done concurrent with pushing out the new version to the production environment.

**Comment by dpemmerich** [comment]
we have a new student starting this week, care if I assign this to her when she starts?

**Comment by dpemmerich** [comment]
@shreyad216 did you get a chance to finish this?

**Comment by shreyad216** [comment]
Yes, this is completed and merged with the development branch
