### ISSUE TITLE
Edit Mode: Add file URL Doesn't Enable SAVE/PUBLISH

### ISSUE THREAD

**Issue by lauratinnel** [ITI/searcch#150]
After taking ownership of a record and clicking on Edit New Version, the edit dialogue is displayed. 
If you enter an additional file URL, the SAVE and PUBLISH buttons remain inactive.
Entering something in the description field activates these buttons, but then the README.md file is no longer displayed because the description field overwrites it. 

The code should activate the SAVE/PUBLISH buttons if any changes have been made to any field in the record.

**Comment by yashshah15** [comment]
The issue is not reproducible. The save and publish buttons are displayed appropriately.
