### ISSUE TITLE
Read more functionality doesnt work on searcch-frontend-local-dev container

### ISSUE THREAD

**Issue by vivekkarne** [ITI/searcch#33]
**Describe the bug**
After searching for an artifact when we click on read more to get the complete information, it tried to load the artifact but then gives a Error loading message.

**To Reproduce**
1. Go to http://localhost:3000/search
2. Search for ciphertext as keyword
3. Click on read more of first result, gives a Error loading message

**Expected behavior**
The Read more button should present more information about the artifact

**Screenshots**
![Screenshot from 2021-06-11 15-59-14](https://user-images.githubusercontent.com/24715956/121742563-fe63ec80-cacd-11eb-8662-1caa17e6797f.png)
![Screenshot from 2021-06-11 15-59-40](https://user-images.githubusercontent.com/24715956/121742620-0de33580-cace-11eb-9ee9-2d852581a572.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.04
 - Browser [e.g. chrome, safari] Firefox

**Smartphone (please complete the following information):**
 - Version [e.g. 22] 89

**Additional context**
N/A

**Comment by timyardley** [comment]
Fixed in commit 9ad1864a363d9116aa9a3f88020fcb25da5cf8ea, will merge in soon
