### ISSUE TITLE
Add review/rating doesnt send any backend request on the searcch-frontend-local-dev docker setup

### ISSUE THREAD

**Issue by vivekkarne** [ITI/searcch#34]
**Describe the bug**
Add review button doesn't add a review/rating.

**To Reproduce**
1. Go to http://localhost:3000/search
2. Search for ciphertext and locate the first artifact, click on the comment icon on the bottom left corner
3. Enter a review and press send review
4. No request is sent when network section is analyzed with dev tools.
5. Similar behaviour for ratings

**Expected behavior**
A backend request needs to be sent and appropriate rating/review must be added to the database

**Screenshots**
![Screenshot from 2021-06-11 16-01-26](https://user-images.githubusercontent.com/24715956/121743539-7e3e8680-cacf-11eb-827a-19d063d8d5e9.png)
![Screenshot from 2021-06-11 16-01-36](https://user-images.githubusercontent.com/24715956/121743544-7f6fb380-cacf-11eb-95ca-5e4610f6f018.png)
![Screenshot from 2021-06-11 16-06-42](https://user-images.githubusercontent.com/24715956/121743546-80084a00-cacf-11eb-9c9f-f6aef03d41af.png)
![Screenshot from 2021-06-11 16-06-46](https://user-images.githubusercontent.com/24715956/121743551-80a0e080-cacf-11eb-9b38-2a7ab5b49245.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.04
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 89

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by timyardley** [comment]
resolved
