### ISSUE TITLE
Adding an article to favourites sends post request with userid: null

### ISSUE THREAD

**Issue by vivekkarne** [ITI/searcch#35]
**Describe the bug**
Adding an article to favourites  using the heart icon sends a post request with userid: null

**To Reproduce**
1. Login to the localhost:3000 search frontend website using github
2. Search for an artifact and click on favourite icon
3. Use dev tools to observe the request, it sends userid param as null

**Expected behavior**
Artifact must be added to the favourites list

**Screenshots**
Probable cause that userid is null:
![Screenshot from 2021-06-11 16-21-04](https://user-images.githubusercontent.com/24715956/121744761-5a7c4000-cad1-11eb-9e12-8f03915595b3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.04
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 89

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by timyardley** [comment]
resolved
