### ISSUE TITLE
Admin Interface: ability to unpublish/modify/republish artifact

### ISSUE THREAD

**Issue by lauratinnel** [ITI/searcch#42]
Add the ability to, through the admin interface, edit a published artifact. This could be implemented by giving the admin the ability to toggle the publish bit on a single artifact: un-publish, edit, re-publish. This will allow us to quickly hot patch an artifact's hub entry as we work to get good, clean data in this initial phase.

Note: We may want to keep this for future use but by policy should use it judiciously.

**Comment by timyardley** [comment]
@carboxylman admin bypass should satisfy this, commit cf6445fc50c2eb445514206116cde97a9f12ab04 preps the frontend admin side for it, let me know if more is needed beyond that

**Comment by lauratinnel** [comment]
Changed title to reflect what is really needed: admin ability to edit a published artifact. HOW it is implemented is a decision for the dev team.

**Comment by carboxylman** [comment]
Backend now allows this kind of direct edit; changes mtime; does not change original publication metadata.

Once we have versioning, we should probably remove this ability.
