### ISSUE TITLE
UI Change: how relationships are displayed

### ISSUE THREAD

**Issue by lauratinnel** [ITI/searcch#48]
Right now, relationships are displayed using the artifact ID number which isn't very meaningful. We need to rethink how we display these relationships -- perhaps in a list and using the artifact title -- so it is more meaningful to the user.

We may need to also have the ID in the event that there are duplicate titles in the system, although under the covers, if a user clicks on the relationship, the system will take him/her to the the correct related artifact.

**Comment by carboxylman** [comment]
Close by https://github.com/ITI/searcch/pull/161, thanks @ckouder!
