### ISSUE TITLE
UI issue: clarify in role dialogue that multiple authors should be specified separately

### ISSUE THREAD

**Issue by jelenamirkovic** [ITI/searcch#51]
**Describe the bug**
When inputting a new role (new author for manual artifact import) it is unclear to user how to input multiple authors 

**To Reproduce**
1. Go to manual artifact import
2. Click on + for the role
3. Dialogue doesn't make it clear if one can input multiple authors on the same line, like one would for a paper

**Expected behavior**
A line of guidance that says "Input multiple authors separately, one at a time"

**Additional context**
I think we should rename Role to Author since the dialogue is clearly "Add Author".

**Comment by lauratinnel** [comment]
Updated the FAQ and also the best-practices document (searcch.cyberexperimentation.org/best-practices) to clearly state that each author is to be added separately using the + button.
