### ISSUE TITLE
Add link from hub to the CCRI-VO website

### ISSUE THREAD

**Issue by eeide** [ITI/searcch#67]
**Describe the solution you'd like**
At an appropriate place in the SEARCCH hub website, add a link to the CCRI-VO website, https://www.ccrivo.org/

Maybe at the bottom of the front page and in the FAQ, add something like this:
> The SEARCCH hub is community infrastructure supported by the National Science Foundation's CCRI and SATC programs. Visit the [CCRI-VO website](https://www.ccrivo.org/) to discover other infrastructure supported by the CCRI program.

**Background**
NSF has funded a "CCRI Virtual Organization" (CCRI-VO). As described at its website, https://www.ccrivo.org/about/

> The CCRI Virtual Organization (CCRI-VO) exists to help users understand and utilize the many different computing infrastructures available to them under CCRI. To achieve this purpose, CCRI-VO keeps a centralized list of infrastructures that CCRI has funded, as well as documentation for using those infrastructures.

Eric Eide is a current member of the the CCRI-VO Council (i.e., advisory board).

To help increase the visibility of its website, the CCRI-VO is asking CCRI-supported projects to link from their websites to to the CCRI-VO website.

Aside, here is the (partial) description of SEARCCH in the CCRI-VO website: https://www.ccrivo.org/projects/sharing-expertise-and-artifacts-reuse-through-cybersecurity-communityhub-searcch/

Eric Eide is "on the hook" for helping the CCRI-VO complete this entry. He'll probably be asking for help!

**Comment by hardiksurana** [comment]
PR: https://github.com/ITI/searcch/pull/98
