### ISSUE TITLE
Display contents of readme.MD file for artifacts of type data (Source: BETA Test)

### ISSUE THREAD

**Issue by lauratinnel** [ITI/searcch#76]
readme.MD only shows up for code. Needs to show up for data.

**Comment by eeide** [comment]
Do you mean that the importer doesn't capture the contents for `README.md`? Or do you mean that the front end does not display it? (Or both?)

**Comment by lauratinnel** [comment]
The front end doesn't display it.

**Comment by carboxylman** [comment]
Fixed in 6619ec6.
