### ISSUE TITLE
Search Artifacts UI: "Back to Top" button can occlude "Read More" button

### ISSUE THREAD

**Issue by eeide** [ITI/searcch#95]
**Describe the bug**
On the "Search Artifacts" page, the "Back to Top" button can cover up the "Read More" button for an artifact. See the attached screenshot.

**To Reproduce**
1. Go to "Search Artifacts"
2. Search for "stackdb"
3. Scroll the window content down to the bottom

**Expected behavior**
The window content would scroll up enough so that the "Read More" button for the last artifact would be clickable.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Firefox 93.0

<img width="1301" alt="Screen Shot 2021-10-12 at 2 34 36 PM" src="https://user-images.githubusercontent.com/160140/137034693-12c12fef-dd67-42e2-b23a-98be5cf13127.png">

**Comment by carboxylman** [comment]
I am not a vuetify nor css wizard, but IMO here are the reasonable possibilities:
  * center the "Back to Top" button
  * left-justify the Top button
  * left-justify the artifact action buttons (e.g. Read More)
  * remove the button

The list of artifacts is its own vue "card", and the button is in that component, so we cannot for instance move it into the navbar or the footer (cards/components facilitate reuse).

I did try moving the button to the extreme "bottom" and "right" (up against scrollbar), but that only results in a partially-occluded "Read More" button.

**Comment by carboxylman** [comment]
I addressed this in 38149f8.
![foo](https://user-images.githubusercontent.com/5054696/143138968-f7ac4c1d-b8d5-434e-8014-36246c8bc7ef.jpg)

**Comment by carboxylman** [comment]
Let's see if this is "good enough"; reopen if not :)
