### ISSUE TITLE
FE support for searching for users, artifacts and organizations

### ISSUE THREAD

**Issue by hardiksurana** [ITI/searcch#99]
1. Need to create a multi-select dropdown with options for **artifact**, **user**, and **organization**.
2. Pass the selected options under the **entity** list to the /artifact/search endpoint
3. Render the list of artifacts, users and/or organizations returned under separate headings/tabs in the UI.

**Comment by carboxylman** [comment]
I split out author vs owner and made owner visible to admins only in 157a7006 .  Backend support in https://github.com/ITI/searcch-backend/commit/e317eabce3033caf2bd0af58a0d7fb1e2dc06bd7, https://github.com/ITI/searcch-backend/commit/5b5c377fff7ae63237ca3a3516bc2769ffe5877a, https://github.com/ITI/searcch-backend/commit/a5966397ae1c805e398cd747679178db18fad839 .
